### ISSUE TITLE
Create base React HMR, Webpack application

### ISSUE THREAD

**Issue by ChrisCates** [LamdaFu/flatbuffers-visual#2]
Should have a basic webpack HMR boilerplate application to work off of.

**Comment by ChrisCates** [comment]
@mpouttuclarke Completed please review

**Comment by mpouttuclarke** [comment]
Matts-MacBook:flatbuffers-visual matt$ npm start

> flatbuffers-visual@1.0.0 start /Users/matt/git/flatbuffers-visual
> node server.js

module.js:328
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/matt/git/flatbuffers-visual/server.js:1:77)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! flatbuffers-visual@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flatbuffers-visual@1.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the flatbuffers-visual package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls flatbuffers-visual
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/matt/git/flatbuffers-visual/npm-debug.log

**Comment by ChrisCates** [comment]
@mpouttuclarke Updated documentation, let me know when you got it working :)

**Comment by mpouttuclarke** [comment]
@ChrisCates: Looks like the smoke test app is working, after I added the webpack-dev-server to the install and it worked.

**Comment by ChrisCates** [comment]
@mpouttuclarke Okay, closing issue now. Reopen if there's any issues.
